name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Prepare deployment
        run: |
          mkdir deploy

          cp index.html deploy/

          cp -r campaigns deploy/
          cp -r css deploy/
          cp -r js deploy/

          touch deploy/.nojekyll

      - name: Upload website
        uses: actions/upload-pages-artifact@v4
        with:
          path: "deploy"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
